//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/5/27 19:54:32
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace BaseDB
{
    /// <summary>
    /// There are no comments for BaseDB.用户_角色 in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class 用户_角色 : Util.Model.Base_Entity, ICloneable {

        /// <summary>
        /// There are no comments for 用户_角色 constructor in the schema.
        /// </summary>
        public 用户_角色()
        {
            OnCreated();
        }

        /// <summary>
        /// There are no comments for Key in the schema.
        /// </summary>
        public virtual string Key { get; set; }

        /// <summary>
        /// There are no comments for 用户Key in the schema.
        /// </summary>
        public virtual string 用户Key { get; set; }

        /// <summary>
        /// There are no comments for 角色Key in the schema.
        /// </summary>
        public virtual string 角色Key { get; set; }

        /// <summary>
        /// There are no comments for 用户 in the schema.
        /// </summary>
        public virtual 用户 用户 { get; set; }

        /// <summary>
        /// There are no comments for 角色 in the schema.
        /// </summary>
        public virtual 角色 角色 { get; set; }

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          用户_角色 toCompare = obj as 用户_角色;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Key, toCompare.Key))
            return false;
          if (!Object.Equals(this.用户Key, toCompare.用户Key))
            return false;
          if (!Object.Equals(this.角色Key, toCompare.角色Key))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Key.GetHashCode();
          hashCode = (hashCode * 7) + 用户Key.GetHashCode();
          hashCode = (hashCode * 7) + 角色Key.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            用户_角色 obj = new 用户_角色();
            obj.Key = Key;
            obj.用户Key = 用户Key;
            obj.角色Key = 角色Key;
            return obj;
        }

        #endregion
    }

}
