//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/5/27 19:54:32
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace BaseDB
{
    /// <summary>
    /// There are no comments for BaseDB.组织 in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class 组织 : Util.Model.Base_Entity, ICloneable {

        /// <summary>
        /// There are no comments for 组织 constructor in the schema.
        /// </summary>
        public 组织()
        {
            this.下辖的用户列表 = new List<用户_组织>();
            this.下级组织列表 = new List<组织>();
            OnCreated();
        }

        /// <summary>
        /// There are no comments for Key in the schema.
        /// </summary>
        public new string Key { get; set; }

        /// <summary>
        /// There are no comments for 编号 in the schema.
        /// </summary>
        public virtual string 编号 { get; set; }

        /// <summary>
        /// There are no comments for 序号 in the schema.
        /// </summary>
        public virtual int 序号 { get; set; }

        /// <summary>
        /// There are no comments for 名称 in the schema.
        /// </summary>
        public virtual string 名称 { get; set; }

        /// <summary>
        /// There are no comments for 全名 in the schema.
        /// </summary>
        public virtual string 全名 { get; set; }

        /// <summary>
        /// There are no comments for 上级组织Key in the schema.
        /// </summary>
        public virtual string 上级组织Key { get; set; }

        /// <summary>
        /// There are no comments for 下辖的用户列表 in the schema.
        /// </summary>
        public virtual IList<用户_组织> 下辖的用户列表 { get; set; }

        /// <summary>
        /// There are no comments for 下级组织列表 in the schema.
        /// </summary>
        public virtual IList<组织> 下级组织列表 { get; set; }

        /// <summary>
        /// There are no comments for 上级组织 in the schema.
        /// </summary>
        public virtual 组织 上级组织 { get; set; }

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          组织 toCompare = obj as 组织;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Key, toCompare.Key))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Key.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            组织 obj = new 组织();
            obj.Key = Key;
            obj.编号 = 编号;
            obj.序号 = 序号;
            obj.名称 = 名称;
            obj.全名 = 全名;
            obj.上级组织Key = 上级组织Key;
            return obj;
        }

        #endregion
    }

}
