//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/5/27 19:54:32
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json.Serialization;

namespace BaseDB
{
    /// <summary>
    /// There are no comments for BaseDB.菜单 in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    [Serializable()]
    public partial class 菜单 : Util.Model.Base_Entity, ICloneable {

        /// <summary>
        /// There are no comments for 菜单 constructor in the schema.
        /// </summary>
        public 菜单()
        {
            this.下级菜单列表 = new List<菜单>();
            this.可访问的角色列表 = new List<角色_菜单>();
            OnCreated();
        }

        /// <summary>
        /// There are no comments for Key in the schema.
        /// </summary>
        public virtual string Key { get; set; }

        /// <summary>
        /// There are no comments for 名称 in the schema.
        /// </summary>
        public virtual string 名称 { get; set; }

        /// <summary>
        /// There are no comments for 编号 in the schema.
        /// </summary>
        public virtual string 编号 { get; set; }

        /// <summary>
        /// There are no comments for 序号 in the schema.
        /// </summary>
        public virtual int 序号 { get; set; }

        /// <summary>
        /// There are no comments for Url in the schema.
        /// </summary>
        public virtual string Url { get; set; }

        /// <summary>
        /// There are no comments for ICON in the schema.
        /// </summary>
        public virtual string ICON { get; set; }

        /// <summary>
        /// There are no comments for 上级菜单Key in the schema.
        /// </summary>
        public virtual string 上级菜单Key { get; set; }

        /// <summary>
        /// There are no comments for 下级菜单列表 in the schema.
        /// </summary>
        public virtual IList<菜单> 下级菜单列表 { get; set; }

        /// <summary>
        /// There are no comments for 上级菜单 in the schema.
        /// </summary>
        public virtual 菜单 上级菜单 { get; set; }

        /// <summary>
        /// There are no comments for 可访问的角色列表 in the schema.
        /// </summary>
        public virtual IList<角色_菜单> 可访问的角色列表 { get; set; }

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          菜单 toCompare = obj as 菜单;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Key, toCompare.Key))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Key.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            菜单 obj = new 菜单();
            obj.Key = Key;
            obj.名称 = 名称;
            obj.编号 = 编号;
            obj.序号 = 序号;
            obj.Url = Url;
            obj.ICON = ICON;
            obj.上级菜单Key = 上级菜单Key;
            return obj;
        }

        #endregion
    }

}
