//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 2022/5/19 17:14:38
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using BaseDB;
using System;

namespace IRepository_DB
{
    public partial interface IUnitOfWork : IDisposable
    {
        IRepository<菜单> 菜单 { get; }
        IRepository<附件> 附件 { get; }
        IRepository<角色> 角色 { get; }
        IRepository<角色_菜单> 角色_菜单s { get; }
        IRepository<用户_组织> 用户_组织s { get; }
        IRepository<用户_角色> 用户_角色s { get; }
        IRepository<用户> 用户 { get; }
        IRepository<组织> 组织 { get; }
        void Save();
    }
}
