//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/5/19 17:14:38
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BaseDB
{
    /// <summary>
    /// There are no comments for 附件Configuration in the schema.
    /// </summary>
    [GeneratedCode("Devart Entity Developer", "")]
    public partial class 附件Configuration : IEntityTypeConfiguration<附件>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<附件> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<附件> builder)
        {
            builder.ToTable(@"附件");
            builder.Property(x => x.Key).HasColumnName(@"Key").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.Category).HasColumnName(@"Category").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.Title).HasColumnName(@"Title").ValueGeneratedNever().HasMaxLength(200);
            builder.Property(x => x.FileName).HasColumnName(@"FileName").IsRequired().ValueGeneratedNever().HasMaxLength(200).HasDefaultValueSql(@"''");
            builder.Property(x => x.Extension).HasColumnName(@"Extension").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.Size).HasColumnName(@"Size").IsRequired().ValueGeneratedNever().HasPrecision(19, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.ContentType).HasColumnName(@"ContentType").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.FilePath).HasColumnName(@"FilePath").ValueGeneratedNever().HasMaxLength(200);
            builder.Property(x => x.Hash).HasColumnName(@"Hash").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.UploadTime).HasColumnName(@"UploadTime").ValueGeneratedNever();
            builder.Property(x => x.Source).HasColumnName(@"Source").ValueGeneratedNever().HasMaxLength(500);
            builder.HasKey(@"Key");

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<附件> builder);

        #endregion
    }

}
