//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2022/5/27 19:54:32
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

/// <summary>
/// There are no comments for 角色_菜单Configuration in the schema.
/// </summary>
[GeneratedCode("Devart Entity Developer", "")]
public partial class 角色_菜单Configuration : IEntityTypeConfiguration<角色_菜单>
{
    /// <summary>
    /// There are no comments for Configure(EntityTypeBuilder<角色_菜单> builder) method in the schema.
    /// </summary>
    public void Configure(EntityTypeBuilder<角色_菜单> builder)
    {
        builder.ToTable(@"角色_菜单");
        builder.Property(x => x.Key).HasColumnName(@"Key").IsRequired().ValueGeneratedNever();
        builder.Property(x => x.角色Key).HasColumnName(@"角色Key").IsRequired().ValueGeneratedNever();
        builder.Property(x => x.菜单Key).HasColumnName(@"菜单Key").IsRequired().ValueGeneratedNever();
        builder.HasKey(@"Key", @"角色Key", @"菜单Key");
        builder.HasOne(x => x.角色).WithMany(op => op.可访问的菜单列表).HasForeignKey(@"角色Key").IsRequired(true);
        builder.HasOne(x => x.菜单).WithMany(op => op.可访问的角色列表).HasForeignKey(@"菜单Key").IsRequired(true);

        CustomizeConfiguration(builder);
    }

    #region Partial Methods

    partial void CustomizeConfiguration(EntityTypeBuilder<角色_菜单> builder);

    #endregion
}
