using System;
using System.Collections.Generic;
using System.Text;

namespace MES.InformationObject
{
    /// <summary>
    /// todo 待翻译
    /// </summary>
    public enum InformationObjectTypeType
    {
        Change,
        Comment,
        DataSet,
        Event,
        OperationalLocation,
        OperationalLocationClass,
        PersonnelClass,
        Person,
        EquipmentClass,
        Equipment,
        PhysicalAssetClass,
        PhysicalAsset,
        MaterialClass,
        MaterialDefinition,
        MaterialLot,
        MaterialSubLot,
        ProcessSegment,
        TestSpecification,
        TestResult,
        Sample,
        PropertyMeasurement,
        OperationsEventClass,
        OperationsEventDefinition,
        OperationsEvent,
        OperationsDefinition,
        OperationsSegment,
        OperationsSchedule,
        OperationsRequest,
        OperationsPerformance,
        OperationsResponse,
        OperationsCapability,
        ResourceRelationshipNetwork,
        ResourceNetworkConnectionType,
        WorkMaster,
        WorkDirective,
        WorkflowSpecification,
        WorkflowSpecificationNodeType,
        WorkflowSpecificationConnectionType,
        WorkSchedule,
        WorkRequest,
        JobList,
        JobOrder,
        WorkPerformance,
        WorkResponse,
        JobResponse,
        JobResponseList,
        WorkCapability,
        WorkMasterCapability,
        WorkAlertDefinition,
        WorkAlert,
        WorkCalendar,
        WorkCalendarDefinition,
        WorkRecord,
        WorkRecordSpecification,
        BatchProductionRecord,
        ControlRecipe,
        MasterRecipe,
        GRecipe,
        RecipeElement,
        ResourceConstraint,
        ProcessElement,
        PersonnelIdentificationManifest,
        ResourceDefinitionManifest,
        Other,
    }
}
